### ISSUE TITLE
Release v1.2.0

### ISSUE THREAD

**Issue by Rehre** [Rehre/Katou-bot#5]
# TODO

- [x] add prettier and eslint
- [x] replace request-promise with node-fetch
- [x] update dev dependencies
- [x] update dependencies
- [x] improve error handling
- [x] update LINE and TELEGRAM keyword list
